### ISSUE TITLE
Does MULTI/EXEC support CREATE queries

### ISSUE THREAD

**Issue by JoonasC** [RedisGraph/JRedisGraph#100]
It seems like MULTI/EXEC doesn't support CREATE queries, is this normal, or am I doing something wrong?

Code sample (Kotlin):
```kotlin
redisGraph.context.use { context ->
  context.multi().use { tx ->
    tx
    .query(
       "testGraph",
       """
           CREATE (:VARIABLE {id:${"$"}id})
       """.trimIndent(),
       mapOf("id" to "test")
    )
    tx.exec()
  }
}
```

**Comment by swilly22** [comment]
Hi @JoonasC, I have no experience in Java / Kotlin but you should be able to run write queries whin a MULTI/EXEC transection,
```
127.0.0.1:6379> multi
OK
127.0.0.1:6379> GRAPH.QUERY g "CREATE (:VARIABLE {id:1})"
QUEUED
127.0.0.1:6379> exec
1) 1) 1) "Labels added: 1"
      2) "Nodes created: 1"
      3) "Properties set: 1"
      4) "Cached execution: 0"
      5) "Query internal execution time: 0.948000 milliseconds"
```

Can you share the output you're seeing?

**Comment by JoonasC** [comment]
Well, I'm not really getting any output since this library doesn't have logging, but running the above query without a transaction works as intended.

```kotlin
redisGraph.context.use { context ->
  context
  .query(
    "testGraph",
    """
         CREATE (:VARIABLE {id:${"$"}id})
    """.trimIndent(),
    mapOf("id" to "test")
  )
}
```
```
127.0.0.1:49335> GRAPH.QUERY testGraph "MATCH (n) RETURN n"
1) 1) "n"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) 1) "VARIABLE"
         3) 1) "properties"
            2) 1) 1) "id"
                  2) "test"
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 6.332984 milliseconds"
```

Running the query with the transaction creates no nodes:
```
127.0.0.1:49348> GRAPH.QUERY testGraph "MATCH (n) RETURN n"
1) 1) "n"
2) (empty list or set)
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 1.093733 milliseconds"
```

**Comment by DvirDukhan** [comment]
@JoonasC 
I'm not really familiarized with Kotlin, however, in your code, you are accessing `redisGraph.context`
maybe try `redisGraph.getContext()`. Is `redisGraph.context` call is equivalent to the getter call?
in our tests we do perform write query in `MULTI/EXEC` execution context via:
` RedisGraphTransaction transaction = api.getContext().multi();`

**Comment by JoonasC** [comment]
@DvirDukhan `context` is equivalent to `getContext`

**Comment by JoonasC** [comment]
In Kotlin, that is

**Comment by DvirDukhan** [comment]
ok I'll have a look

**Comment by DvirDukhan** [comment]
is the expression `pi.getContext().multi();` equivilant to the example that you sent?

**Comment by JoonasC** [comment]
Yes, `.use` is another feature of kotlin, which closes the object after the lambda function is complete. Similarly to a try with resources.

**Comment by sazzad16** [comment]
@JoonasC I'm not sure if it's redundant here at this point. But if you check the test codes, MULTI/EXEC has been tested including CREATE. Could you please check if your code is properly translated to Kotlin?

https://github.com/RedisGraph/JRedisGraph/blob/a0f077f12378619ad56b28d44c6b57bfaf783a86/src/test/java/com/redislabs/redisgraph/RedisGraphAPITest.java#L504-L514

**Comment by JoonasC** [comment]
@sazzad16 I think it should be properly translated.

The following sample project recreates the issue for me, when using the latest dockerized redisgraph version: [https://drive.google.com/file/d/1CZUBz2lInUJKR8VICrA3m8qtakfDYTG4/view?usp=sharing](https://drive.google.com/file/d/1CZUBz2lInUJKR8VICrA3m8qtakfDYTG4/view?usp=sharing).

**Comment by JoonasC** [comment]
@swilly22 @sazzad16 @DvirDukhan Ok, after some testing, it seems like the issue has something to do with passing the arguments to the query through a map, such as:
```java
import com.redislabs.redisgraph.RedisGraphContext;
import com.redislabs.redisgraph.RedisGraphTransaction;
import com.redislabs.redisgraph.impl.api.RedisGraph;

import java.util.HashMap;
import java.util.Map;

public class Application {
    public static void main(String[] args) {
        RedisGraph redisGraph = new RedisGraph();
        RedisGraphContext context = redisGraph.getContext();
        RedisGraphTransaction tx = context.multi();
        Map<String, Object> params = new HashMap<>();
        params.put("id", 1);
        tx.query("testGraph", "CREATE (:VARIABLE {id:$id})", params);
        tx.exec();
        context.close();
    }
}
```

The above Java code has the same issue as my Kotlin examples.

**Comment by DvirDukhan** [comment]
@JoonasC 
can you please specify the graph version that you are working with?

Tested on `latest` docker image

```java
package com.redislabs.redisgraph.impl;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.HashMap;
import java.util.Map;

import com.redislabs.redisgraph.Record;
import com.redislabs.redisgraph.RedisGraphContext;
import com.redislabs.redisgraph.RedisGraphContextGenerator;
import com.redislabs.redisgraph.RedisGraphTransaction;
import com.redislabs.redisgraph.ResultSet;
import com.redislabs.redisgraph.impl.api.RedisGraph;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

public class TransactionTest {

    private RedisGraphContextGenerator api;
    private final String graphKey = "testGraph";

    @Before
    public void createApi() {
        api = new RedisGraph();
        // Dummy query just to set a graph in the keyspace;
        api.query(graphKey, "MATCH (n) RETURN n");
    }

    @After 
    public  void closeApi(){
        api.deleteGraph(graphKey);
        api.close();
    }

    @Test
    public void testTransaction(){
        RedisGraphContext context = api.getContext();
        RedisGraphTransaction tx = context.multi();
        Map<String, Object> params = new HashMap<>();
        params.put("id", 1);
        tx.query(graphKey, "CREATE (:VARIABLE {id:$id})", params);
        tx.exec();
        context.close();

        ResultSet rs = api.query(graphKey, "MATCH (n) RETURN COUNT(n)");
        assertEquals(1, rs.size());
        while(rs.hasNext()){
            Record r = rs.next();
            assertEquals(1L, ((Long) (r.getValue(0))).longValue());
        }
        rs = api.query(graphKey, "MATCH (n) RETURN n");
        assertEquals(1, rs.size());
        Record r = rs.next();
        assertEquals("Record{values=[Node{labels=[VARIABLE], id=0, propertyMap={id=Property{name='id', value=1}}}]}", r.toString());
    }
}

```

**Comment by JoonasC** [comment]
@DvirDukhan I'm also using the `latest` docker image version.

Does the issue not manifest on your end?

**Comment by JoonasC** [comment]
@DvirDukhan Any updates?

**Comment by DvirDukhan** [comment]
@JoonasC 
The unit test that I added pass on my end with fresh `latest` docker. Can you please provide the output of `module list` with the RedisGraph version?

**Comment by JoonasC** [comment]
Here you go:
```
127.0.0.1:6379> module list
1) 1) "name"
   2) "graph"
   3) "ver"
   4) (integer) 20212
```

**Comment by JoonasC** [comment]
@DvirDukhan Btw, did the demo project that I shared earlier (https://github.com/RedisGraph/JRedisGraph/issues/100#issuecomment-752947057) produce the same issue on your end?

**Comment by DvirDukhan** [comment]
can you provide a GitHub repository?

**Comment by JoonasC** [comment]
@DvirDukhan I shared a download link to a zip-file. Are you unable to use that?

**Comment by JoonasC** [comment]
@DvirDukhan ?

**Comment by DvirDukhan** [comment]
@JoonasC  sorry, I was not working on RedisGraph today. I will give it a look tomorrow

**Comment by DvirDukhan** [comment]
@JoonasC 
upgrade you dependencies to 
```
dependencies {
    implementation(kotlin("stdlib"))
    implementation("com.redislabs:jredisgraph:2.2.0")
    implementation("redis.clients:jedis:3.4.1")
}
```

output:
```
11:33:00 AM: Executing task 'ApplicationKt.main()'...

> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE

> Task :ApplicationKt.main()
Id from database: test
Id from database: test

BUILD SUCCESSFUL in 501ms
2 actionable tasks: 1 executed, 1 up-to-date
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
11:33:00 AM: Task execution finished 'ApplicationKt.main()'.
```

**Comment by JoonasC** [comment]
@DvirDukhan @sazzad16 Unfortunately I'm still getting the following output:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Id from database: test
Exception in thread "main" java.util.NoSuchElementException
	at com.redislabs.redisgraph.impl.resultset.ResultSetImpl.next(ResultSetImpl.java:287)
	at com.redislabs.redisgraph.impl.resultset.ResultSetImpl.next(ResultSetImpl.java:19)
	at ApplicationKt.main(Application.kt:62)
	at ApplicationKt.main(Application.kt)

Process finished with exit code 1
```

Could using openjdk version 11 have something to do with it?

**Comment by JoonasC** [comment]
@DvirDukhan @sazzad16 Ok, that seems to have fixed it. Thanks!
