### ISSUE TITLE
redis.clients.jedis.exceptions.JedisConnectionException is reported when executing the Cypher queries.

### ISSUE THREAD

**Issue by abc123000111** [RedisGraph/JRedisGraph#136]
Hello, I discovered that when I executed the queries in the attached java file, an exception occurred:
[redisgraph.zip](https://github.com/RedisGraph/JRedisGraph/files/7733599/redisgraph.zip)

**Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.**
at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43)
at redis.clients.jedis.Protocol.process(Protocol.java:158)
at redis.clients.jedis.Protocol.read(Protocol.java:223)
at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352)
at redis.clients.jedis.Connection.getOne(Connection.java:330)
at redis.clients.jedis.Jedis.sendCommand(Jedis.java:4559)
at com.redislabs.redisgraph.impl.api.ContextedRedisGraph.sendQuery(ContextedRedisGraph.java:52)
at com.redislabs.redisgraph.impl.api.RedisGraph.sendQuery(RedisGraph.java:68)
at com.redislabs.redisgraph.impl.api.AbstractRedisGraph.query(AbstractRedisGraph.java:63)
at RedisGraphExample.main(RedisGraphExample.java:32)

But if I comment out some of the queries, no error will be reported. And if these queries do not contain WHERE clauses, no error will be reported. I wonder if it is a bug. Thanks a lot!

RedisGraph Version: 2.4.11 Docker
Operating System: Windows 11
API: Cypher/Java API
JRedisGraph Version: 2.5.1

**Comment by abc123000111** [comment]
> @abc123000111 Without the graph (and may be some understanding of that graph) and more information, it is difficult to check.
> 
> It could be as simple as a slow query with a short socket timeout.

 Hello! The initial database state is empty. But when I execute the program, the exception is reported. However, if I comment out some of the queries or remove all WHERE clauses, no exception will be reported. 

If the root cause is a slow query with a short socket timeout, how to solve it and keep connection?

**Comment by sazzad16** [comment]
@abc123000111 Seems to be RedisGraph issue. [Commented there](https://github.com/RedisGraph/RedisGraph/issues/2068#issuecomment-1041135905).

**Comment by abc123000111** [comment]
> @abc123000111 Seems to be RedisGraph issue. [Commented there](https://github.com/RedisGraph/RedisGraph/issues/2068#issuecomment-1041135905).

Thank you!
