### ISSUE TITLE
How do i connect to a secure redis instance?

### ISSUE THREAD

**Issue by anishGoMMT** [RedisGraph/JRedisGraph#24]
No option provided in the RedisGraphAPI constructor to pass auth.

Executing a query fails with following error on an redis instance with auth enabled:
Exception in thread "main" redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
	at redis.clients.jedis.Protocol.processError(Protocol.java:131)
	at redis.clients.jedis.Protocol.process(Protocol.java:165)
	at redis.clients.jedis.Protocol.read(Protocol.java:219)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:309)
	at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:276)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:280)
	at com.redislabs.redisgraph.RedisGraphAPI.query(RedisGraphAPI.java:47)

**Comment by gkorland** [comment]
You should use the 

```
    public RedisGraphAPI(String graphId, Pool<Jedis> jedis) {
```
