### ISSUE TITLE
Create a new vertex and return its id

### ISSUE THREAD

**Issue by tperry** [RedisGraph/JRedisGraph#27]
When creating a new vertex is it possible to get the id of the newly created vertex. I've tried the following but it throws a JedisDataException.

ResultSet rs = api.query( "CREATE (p:person{name:'rois', age:32}) RETURN ID(p))");

Exception in thread "main" redis.clients.jedis.exceptions.JedisDataException: Syntax error at offset 46 near 'RETURN'
	at redis.clients.jedis.Protocol.processError(Protocol.java:131)
	at redis.clients.jedis.Protocol.process(Protocol.java:165)
	at redis.clients.jedis.Protocol.read(Protocol.java:219)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:309)
	at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:276)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:280)
	at com.redislabs.redisgraph.RedisGraphAPI.query(RedisGraphAPI.java:58)

What's the correct way to do this?

**Comment by gkorland** [comment]
https://github.com/RedisGraph/JRedisGraph/issues/27
