### ISSUE TITLE
Path Query gives ArrayOutOfBoundsException with redisgraph:edge docker version

### ISSUE THREAD

**Issue by arramos84** [RedisGraph/JRedisGraph#83]
When running a query like:

```
"MATCH p=(n:Container)<-[*0..10]-(m) WHERE n.name='c0' AND (n._updated >= 100000 AND n._created <= 100000) RETURN p"
```

It looks like we are intermittently getting this exception only with the newest redisgraph `edge` version:

```
Index -2 out of bounds for length 1
java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 1
	at java.base/java.util.concurrent.CopyOnWriteArrayList.elementAt(CopyOnWriteArrayList.java:385)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:398)
	at com.redislabs.redisgraph.impl.graph_cache.GraphCacheList.getCachedData(GraphCacheList.java:45)
	at com.redislabs.redisgraph.impl.graph_cache.GraphCache.getLabel(GraphCache.java:30)
	at com.redislabs.redisgraph.impl.resultset.ResultSetImpl.deserializeNode(ResultSetImpl.java:148)
	at com.redislabs.redisgraph.impl.resultset.ResultSetImpl.deserializeScalar(ResultSetImpl.java:240)
	at com.redislabs.redisgraph.impl.resultset.ResultSetImpl.deserializeArray(ResultSetImpl.java:262)
	at com.redislabs.redisgraph.impl.resultset.ResultSetImpl.deserializeScalar(ResultSetImpl.java:238)
	at com.redislabs.redisgraph.impl.resultset.ResultSetImpl.deserializePath(ResultSetImpl.java:253)
	at com.redislabs.redisgraph.impl.resultset.ResultSetImpl.deserializeScalar(ResultSetImpl.java:244)
	at com.redislabs.redisgraph.impl.resultset.ResultSetImpl.parseResult(ResultSetImpl.java:90)
	at com.redislabs.redisgraph.impl.resultset.ResultSetImpl.<init>(ResultSetImpl.java:55)
	at com.redislabs.redisgraph.impl.api.ContextedRedisGraph.sendQuery(ContextedRedisGraph.java:53)
	at com.redislabs.redisgraph.impl.api.RedisGraph.sendQuery(RedisGraph.java:68)
	at com.redislabs.redisgraph.impl.api.AbstractRedisGraph.query(AbstractRedisGraph.java:39)
	at ai.asserts.model.redis.RedisKGraph.getEntityWithUplinks(RedisKGraph.java:178)
	at ai.asserts.model.graph.KGraphTest$UplinkMatchTest.redis_test(KGraphTest.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:413)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

We suspect the newer version triggered the issue in the client, but can't be 100%. Currently trying to deconstruct the series of queries that surfaced this as it seems to only occur with a specific ordering of queries. Hoping that maybe there is something known on your end.

All other previous versions didn't show this issue. Thanks for any help. 

@DvirDukhan

**Comment by DvirDukhan** [comment]
Hi @arramos84
As you can see, we have an ileagal access in an array
```
java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 1
```
In this case, the JRedisGraph local cache is trying to map between a node label id and a label string representation. The `-2` index value is an internal redisgraph definition for unkown label. https://github.com/RedisGraph/RedisGraph/blob/068c4259afebd17b0c99b17be50c7a387ad006b5/src/graph/graph.h#L25
```c
#define GRAPH_UNKNOWN_LABEL -2 
```
We had similar issue on edges which was fixed in https://github.com/RedisGraph/RedisGraph/pull/1282
Can you please provide a sample dataset or simple data creation flow in order to reproduce, regardless to JRedisGraph? Can you try a simple repeoduction on CLI/other RedisGraph client library?
I suspect it is a RedisGraph issue rather than a JRedisGraph. Please leave this issue open until we can decide where this issue belongs to.

**Comment by arramos84** [comment]
Sounds good, thanks! Will try to dupe on the cli side now that I have some more context.

**Comment by arramos84** [comment]
@DvirDukhan , here is a series of tests that induce a failure:

```
package ai.asserts.model.redis;

import com.redislabs.redisgraph.ResultSet;
import com.redislabs.redisgraph.Statistics;
import com.redislabs.redisgraph.impl.api.RedisGraph;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.images.PullPolicy;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@Testcontainers
class RedisGraphTest {

    @Container
    private static final GenericContainer redisServer =
            new GenericContainer<>("redislabs/redisgraph:edge")
                    .withImagePullPolicy(PullPolicy.alwaysPull())
                    .withExposedPorts(6379);

    private static RedisGraph graph;

    @BeforeAll
    static void setUpAll() {
        String redisHost = redisServer.getHost();
        Integer redisPort = redisServer.getFirstMappedPort();
        graph = new RedisGraph(redisHost, redisPort);
    }

    @Test
    void redis_test() {
        ResultSet resultSet = graph.query("test", "MATCH p=(n:Container)<-[*0..10]-(m) WHERE n.name='c0' AND (n._updated >= 100000 AND n._created <= 100000) RETURN p");
        assertTrue(resultSet.size() == 0);

        Map<String, Object> params = new HashMap<>();
        params.put("name", "c0");

        Statistics statistics = graph.query("test", " MERGE (n:Container {name:$name}) ON CREATE SET n._created=100000, n._updated=100000 ON MATCH SET n._updated=100000 ", params).getStatistics();
        assertTrue(statistics.nodesCreated() > 0);

        resultSet = graph.query("test", "MATCH p=(n:Container)<-[*0..10]-(m) WHERE n.name='c0' AND (n._updated >= 100000 AND n._created <= 100000) RETURN p");
        assertTrue(resultSet.size() == 1);

        params = new HashMap<>();
        params.put("name", "c0");
        statistics = graph.query("test", " MERGE (n:Container {name:$name}) ON CREATE SET n._created=100000, n._updated=100000 ON MATCH SET n._updated=100000 ", params).getStatistics();
        assertTrue(statistics.nodesCreated() == 0);


        params.put("name", "p0");
        statistics = graph.query("test", " MERGE (n:Pod {name:$name}) ON CREATE SET n._created=100000, n._updated=100000 ON MATCH SET n._updated=100000 ", params).getStatistics();
        assertTrue(statistics.nodesCreated() > 0);

        params.put("startName", "p0");
        params.put("endName", "c0");
        params.put("cardinality", "OneToMany");
        statistics = graph.query("test", " MATCH (start:Pod {name:$startName}), (end:Container {name:$endName}) MERGE (start)-[r:HOSTS]->(end) ON CREATE SET r._created=100000, r._updated=100000 ON MATCH SET r._updated=100000 SET r.cardinality=$cardinality ", params).getStatistics();
        assertTrue(statistics.relationshipsCreated() > 0);

        resultSet = graph.query("test", "MATCH p=(n:Container)<-[*0..10]-(m) WHERE n.name='c0' AND (n._updated >= 100000 AND n._created <= 100000) RETURN p");
        assertEquals(2,resultSet.size());
    }
}
```

If changing the container image to `:latest`, it will pass. Thanks for the help!

**Comment by arramos84** [comment]
I didn't see an issue when running in the cli, but I may have made an error in translation as the above test seems to pass when just removing or adding read.

**Comment by DvirDukhan** [comment]
@arramos84 PR at RedisGraph https://github.com/RedisGraph/RedisGraph/pull/1358
