### ISSUE TITLE
Exception in quoteString for empty string

### ISSUE THREAD

**Issue by larsrh** [RedisGraph/JRedisGraph#87]
This is the culprit:

https://github.com/RedisGraph/JRedisGraph/blob/4cf34bb314bb15e5e7a7b33019620f3049158405/src/main/java/com/redislabs/redisgraph/impl/Utils.java#L39

If an empty string is passed as a parameter, the code tries to access the 0th character, which fails.

Workaround: use `"\"\""` as parameter (i.e. a string that contains only two quotes).

(NB: I didn't send a PR because I'm not completely sure about the semantics of the the `quoteString` method. Should it escape characters or not?)

**Comment by gkorland** [comment]
@larsrh I'm not sure I get the full scenario, can you please add a short example and the stacktrace?

**Comment by larsrh** [comment]
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:711)
	at com.redislabs.redisgraph.impl.Utils.quoteString(Utils.java:39)
	at com.redislabs.redisgraph.impl.Utils.valueToString(Utils.java:100)
	at com.redislabs.redisgraph.impl.Utils.prepareQuery(Utils.java:82)
	at com.redislabs.redisgraph.impl.api.AbstractRedisGraph.query(AbstractRedisGraph.java:64)
    at (redacted)
```

Triggered by calling `query` with an empty string parameter.

**Comment by gkorland** [comment]
@larsrh See the PR, it seems like the solution was pretty simple the current was code was just trying to be too smart...

**Comment by larsrh** [comment]
Right, that's what I thought. Thanks for the quick turnaround!
